main loop valueerror
Pressing ctrl-c randomly during ripping leads to ValueError.  jack catches
ValueError already in one place, but it needs to do the same in two other
cases.  Debian #352754.

(-) SPACE:1.60GB waiting_WAVs:01 DAE:1+0 ENC:0+1 errors: 15 :-[                                      Traceback (most recent call last):
                                   File "/usr/bin/jack", line 235, in ?
                                                                           global_error = jack_main_loop.main_loop(mp3s_todo, wavs_todo, space, dae_queue, enc_queue, track1_offset)
                                                                                File "/usr/lib/python2.3/site-packages/jack_main_loop.py", line 216, in main_loop
                                                               x = i['file'].read()
                                                                                   ValueError: I/O operation on closed file
                      *warning* abnormal exit
                                             zsh: exit 1     jack
1815:tbm@deprecation: ~/tmp/jack]

Debian patch: 39_main_loop_valueerror.patch