error not block device
Fix an error when the --device passed is a directory.  Debian #360337

$ jack --device=/dev
This is jack 3.1.1 (C)2004 Arne Zellentin <zarne@users.sf.net>
Traceback (most recent call last):
File "/usr/lib/python2.3/site-packages/jack_functions.py", line 148, in gettoc
    exec(jack_helpers.helpers[toc_prog]['toc_fkt'])
  File "<string>", line 11, in ?
IndexError: tuple index out of range
 *error* CDDB.py could not read the disk's TOC. If you already ripped the CD,
         you'll have to cd into the directory which is either named after the
         CD's title or still called jack-xxxxxxxx (xxxxxxxx is a hex number).

Debian patch: 51_error_not_block_device.patch