no tag when freedb fails
Don't try to tag files when no FreeDB data is available - this can
happen when cont_failed_query is set.  Debian #361290

dlakelan@mooch64:~$ jack
This is jack 3.1.1 (C)2004 Arne Zellentin <zarne@users.sf.net>
 *info* querying...
 *warning* 202 No match for disc ID 520ded06. How about trying another
           --server?

freedb search failed, continue? (y/N) y
Options: vbr read-ahead=99 id=520ded06 len=59:25 | press Q to quit
The final status was:
track_01: 12.4x [ DAE done with cdda2wav       ] [coding @16.3x done, 135kbit
track_02: 17.7x [ DAE done with cdda2wav       ] [coding @14.8x done, 129kbit
track_03: 19.7x [ DAE done with cdda2wav       ] [coding @13.0x done, 130kbit
track_04: 23.5x [ DAE done with cdda2wav       ] [coding @16.8x done, 136kbit
track_05: 24.0x [ DAE done with cdda2wav       ] [coding @17.0x done, 132kbit
track_06: 23.5x [ DAE done with cdda2wav       ] [coding @16.7x done, 134kbit
Tagging.Traceback (most recent call last):
  File "/usr/bin/jack", line 274, in ?
    jack_tag.tag(freedb_rename)
  File "/usr/lib/python2.3/site-packages/jack_tag.py", line 182, in tag
    oggi.add_tag('ALBUM', a_title.encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'encode'

Debian patch: 53_no_tag_when_freedb_fails.patch